export const SET_ROUTE_TRANSITION = 'set_route_transition'
export const SET_HOME_ROUTES = 'set_home_routes'
export const SET_PINS_ROUTES = 'set_pins_routes'
export const SET_TOKEN = 'set_token'
export const SET_UID = 'set_uid'
export const SET_IS_LOGIN = 'set_is_login'
export const SET_KEEP_ALIVE_ARR = 'set_keep_alive_arr'
export const SET_QUERY = 'set_query'